### ISSUE TITLE
vx.y.z is not officially the semver format. x.y.z is

### ISSUE THREAD

**Issue by worming004** [maykonlf/semver-cli#18]
Hello,

Officially, semver is not prefixing version with 'v' https://semver.org/#is-v123-a-semantic-version
It is widely used, but not the default one.

Could we have 2 modes ? one with and another without 'v' ?

I could do a PR in few days if you do not mind

**Comment by worming004** [comment]
We are finally using another tool to match our intend. Sorry, I do not intend to create a PR anymore

**Comment by sauljabin** [comment]
@worming004 any recomendation? I need one without the prefix v
